import { Story } from '@/lib/types'

export const akazukinStory: Story = {
  id: 'akazukin',
  title: 'あかずきん',
  coverImage: '/images/akazukin-cover.jpg',
  pages: [
    {
      id: 1,
      pageNumber: 1,
      pageRole: 'タイトルページ',
      fixedElements: ['タイトルと作品紹介'],
      freeElements: ['デザイン', '装飾'],
      illustration: '/images/akazukin/page-01.jpg',
      text: 'あかずきん\n\nせかいの めいさく',
      originalText: 'あかずきん\n\nせかいの めいさく',
      currentText: 'あかずきん\n\nせかいの めいさく',
      alt: '赤いずきんをかぶった女の子が花に囲まれた小さな家の前に立っている',
      isModified: false,
    },
    {
      id: 2,
      pageNumber: 2,
      pageRole: '導入・主人公紹介',
      fixedElements: ['あかずきんという女の子が紹介されること'],
      freeElements: ['住んでいる場所', '家の様子', '日常の風景'],
      illustration: '/images/akazukin/page-02.jpg',
      text: 'むかし むかし、あかい ずきんの おんなのこが いました。\n\nみんなから「あかずきん」と よばれていました。\n\nおかあさんと なかよく くらしていました。',
      originalText: 'むかし むかし、あかい ずきんの おんなのこが いました。\n\nみんなから「あかずきん」と よばれていました。\n\nおかあさんと なかよく くらしていました。',
      currentText: 'むかし むかし、あかい ずきんの おんなのこが いました。\n\nみんなから「あかずきん」と よばれていました。\n\nおかあさんと なかよく くらしていました。',
      alt: 'あかずきんがお母さんと一緒に花でいっぱいの家の前に立っている',
      isModified: false,
    },
    {
      id: 3,
      pageNumber: 3,
      pageRole: 'お使いを頼まれる',
      fixedElements: ['おばあさんの家へお菓子を届けるよう頼まれること'],
      freeElements: ['お菓子の種類', 'かごの見た目', 'おかあさんの言葉'],
      illustration: '/images/akazukin/page-03.jpg',
      text: 'ある ひ、おかあさんが いいました。\n\n「おばあさんの おうちに おかしを とどけて ちょうだい。もりの みちは きを つけてね。」',
      originalText: 'ある ひ、おかあさんが いいました。\n\n「おばあさんの おうちに おかしを とどけて ちょうだい。もりの みちは きを つけてね。」',
      currentText: 'ある ひ、おかあさんが いいました。\n\n「おばあさんの おうちに おかしを とどけて ちょうだい。もりの みちは きを つけてね。」',
      alt: 'お母さんがあかずきんにお菓子の入ったかごを渡している',
      isModified: false,
    },
    {
      id: 4,
      pageNumber: 4,
      pageRole: '森の道を歩く',
      fixedElements: ['森の中を歩いていくこと'],
      freeElements: ['森の風景', '花や鳥', '天気'],
      illustration: '/images/akazukin/page-04.jpg',
      text: 'あかずきんは もりの みちを あるいて いきました。\n\nおはなが きれいに さいていて、ことりが うたっていました。',
      originalText: 'あかずきんは もりの みちを あるいて いきました。\n\nおはなが きれいに さいていて、ことりが うたっていました。',
      currentText: 'あかずきんは もりの みちを あるいて いきました。\n\nおはなが きれいに さいていて、ことりが うたっていました。',
      alt: 'あかずきんが花が咲く森の小道を楽しそうに歩いている',
      isModified: false,
    },
    {
      id: 5,
      pageNumber: 5,
      pageRole: 'オオカミとの出会い',
      fixedElements: ['オオカミと出会い行き先を聞かれること'],
      freeElements: ['オオカミの見た目', '会話の内容', '出会いの場所'],
      illustration: '/images/akazukin/page-05.jpg',
      text: 'すると、おおきな オオカミが あらわれました。\n\n「どこへ いくの、おじょうちゃん？」\n\nオオカミは にこにこ ききました。',
      originalText: 'すると、おおきな オオカミが あらわれました。\n\n「どこへ いくの、おじょうちゃん？」\n\nオオカミは にこにこ ききました。',
      currentText: 'すると、おおきな オオカミが あらわれました。\n\n「どこへ いくの、おじょうちゃん？」\n\nオオカミは にこにこ ききました。',
      alt: '森の中であかずきんが大きなオオカミと向かい合って話している',
      isModified: false,
    },
    {
      id: 6,
      pageNumber: 6,
      pageRole: '寄り道をする',
      fixedElements: ['オオカミに言われて寄り道をすること'],
      freeElements: ['寄り道の理由', '見つけたもの', 'やったこと'],
      illustration: '/images/akazukin/page-06.jpg',
      text: '「あっちに きれいな おはなが さいているよ」と オオカミが いいました。\n\nあかずきんは おはなを つみに よりみちを しました。',
      originalText: '「あっちに きれいな おはなが さいているよ」と オオカミが いいました。\n\nあかずきんは おはなを つみに よりみちを しました。',
      currentText: '「あっちに きれいな おはなが さいているよ」と オオカミが いいました。\n\nあかずきんは おはなを つみに よりみちを しました。',
      alt: 'あかずきんが森の中できれいな花を楽しそうに摘んでいる',
      isModified: false,
    },
    {
      id: 7,
      pageNumber: 7,
      pageRole: 'オオカミが先回り',
      fixedElements: ['オオカミが先におばあさんの家に行くこと'],
      freeElements: ['先回りの方法', '近道の様子'],
      illustration: '/images/akazukin/page-07.jpg',
      text: 'そのあいだに、オオカミは ちかみちで おばあさんの おうちへ さきに いきました。\n\nオオカミは はしって はしって いそぎました。',
      originalText: 'そのあいだに、オオカミは ちかみちで おばあさんの おうちへ さきに いきました。\n\nオオカミは はしって はしって いそぎました。',
      currentText: 'そのあいだに、オオカミは ちかみちで おばあさんの おうちへ さきに いきました。\n\nオオカミは はしって はしって いそぎました。',
      alt: 'オオカミが森の近道を走っておばあさんの家に向かっている',
      isModified: false,
    },
    {
      id: 8,
      pageNumber: 8,
      pageRole: 'オオカミの変装',
      fixedElements: ['オオカミがおばあさんのふりをすること'],
      freeElements: ['変装の様子', 'ベッドの描写'],
      illustration: '/images/akazukin/page-08.jpg',
      text: 'オオカミは おばあさんの ふくを きて、ベッドに もぐりこみました。\n\n「これで ばれないぞ、うっしっし」',
      originalText: 'オオカミは おばあさんの ふくを きて、ベッドに もぐりこみました。\n\n「これで ばれないぞ、うっしっし」',
      currentText: 'オオカミは おばあさんの ふくを きて、ベッドに もぐりこみました。\n\n「これで ばれないぞ、うっしっし」',
      alt: 'オオカミがおばあさんの服を着てベッドに寝ている',
      isModified: false,
    },
    {
      id: 9,
      pageNumber: 9,
      pageRole: 'あかずきん到着',
      fixedElements: ['あかずきんがおばあさんの家に着くこと'],
      freeElements: ['家の様子', '違和感の表現'],
      illustration: '/images/akazukin/page-09.jpg',
      text: 'あかずきんが おばあさんの おうちに つきました。\n\n「おばあさん、おかしを もってきたよ」\n\nドアを あけると、なんだか へんな かんじがしました。',
      originalText: 'あかずきんが おばあさんの おうちに つきました。\n\n「おばあさん、おかしを もってきたよ」\n\nドアを あけると、なんだか へんな かんじがしました。',
      currentText: 'あかずきんが おばあさんの おうちに つきました。\n\n「おばあさん、おかしを もってきたよ」\n\nドアを あけると、なんだか へんな かんじがしました。',
      alt: 'あかずきんがおばあさんの家のドアをノックしている',
      isModified: false,
    },
    {
      id: 10,
      pageNumber: 10,
      pageRole: '正体に気づく',
      fixedElements: ['変装を見破る問答があること'],
      freeElements: ['気づき方', '反応', '緊迫感の表現'],
      illustration: '/images/akazukin/page-10.jpg',
      text: '「おばあさん、おみみが おおきいのね」\n\n「おまえの こえを よく きくためだよ」\n\n「おばあさん、おめめが おおきいのね」\n\n「おまえを よく みるためだよ」\n\nあかずきんは ふしぎに おもいました。',
      originalText: '「おばあさん、おみみが おおきいのね」\n\n「おまえの こえを よく きくためだよ」\n\n「おばあさん、おめめが おおきいのね」\n\n「おまえを よく みるためだよ」\n\nあかずきんは ふしぎに おもいました。',
      currentText: '「おばあさん、おみみが おおきいのね」\n\n「おまえの こえを よく きくためだよ」\n\n「おばあさん、おめめが おおきいのね」\n\n「おまえを よく みるためだよ」\n\nあかずきんは ふしぎに おもいました。',
      alt: 'あかずきんがベッドのそばで変装したオオカミを不思議そうに見ている',
      isModified: false,
    },
    {
      id: 11,
      pageNumber: 11,
      pageRole: '猟師さんが助ける',
      fixedElements: ['猟師が助けに来ること'],
      freeElements: ['助け方', '解決方法', '猟師の登場の仕方'],
      illustration: '/images/akazukin/page-11.jpg',
      text: 'そのとき、りょうしさんが かけつけて きてくれました。\n\n「オオカミめ、わるさは ゆるさんぞ！」\n\nオオカミを おいはらって、おばあさんも ぶじ たすかりました。',
      originalText: 'そのとき、りょうしさんが かけつけて きてくれました。\n\n「オオカミめ、わるさは ゆるさんぞ！」\n\nオオカミを おいはらって、おばあさんも ぶじ たすかりました。',
      currentText: 'そのとき、りょうしさんが かけつけて きてくれました。\n\n「オオカミめ、わるさは ゆるさんぞ！」\n\nオオカミを おいはらって、おばあさんも ぶじ たすかりました。',
      alt: 'たくましい猟師さんが現れてオオカミを追い払い、おばあさんを助けている',
      isModified: false,
    },
    {
      id: 12,
      pageNumber: 12,
      pageRole: 'ハッピーエンド',
      fixedElements: ['ハッピーエンドで終わること'],
      freeElements: ['結末の詳細', '最後のシーン'],
      illustration: '/images/akazukin/page-12.jpg',
      text: 'みんなで なかよく おかしを たべました。\n\n「もう よりみちは しないわ」と あかずきんは やくそくしました。\n\nめでたし めでたし。',
      originalText: 'みんなで なかよく おかしを たべました。\n\n「もう よりみちは しないわ」と あかずきんは やくそくしました。\n\nめでたし めでたし。',
      currentText: 'みんなで なかよく おかしを たべました。\n\n「もう よりみちは しないわ」と あかずきんは やくそくしました。\n\nめでたし めでたし。',
      alt: 'あかずきん、おばあさん、猟師さんが一緒にお茶とお菓子を楽しんでいる',
      isModified: false,
    },
  ],
}
