import { Story } from '@/lib/types'

export const momotaroStory: Story = {
  id: 'momotaro',
  title: 'ももたろう',
  coverImage: '/images/momotaro/page-01.jpg',
  pages: [
    {
      id: 1,
      pageNumber: 1,
      pageRole: 'タイトルページ',
      fixedElements: ['タイトルと作品紹介'],
      freeElements: ['デザイン', '装飾'],
      illustration: '/images/momotaro/page-01.jpg',
      text: 'ももたろう\n\nにほんの むかしばなし',
      originalText: 'ももたろう\n\nにほんの むかしばなし',
      currentText: 'ももたろう\n\nにほんの むかしばなし',
      alt: '大きな桃が川をゆっくり流れている、桜の花びらが舞う美しい風景',
      isModified: false,
    },
    {
      id: 2,
      pageNumber: 2,
      pageRole: '導入・日常',
      fixedElements: ['おじいさんとおばあさんの日常が描かれること'],
      freeElements: ['住んでいる場所', '時代設定', '風景すべて'],
      illustration: '/images/momotaro/page-02.jpg',
      text: 'むかし むかし、ある ところに おじいさんと おばあさんが すんでいました。\n\nおじいさんは やまへ しばかりに、おばあさんは かわへ せんたくに いきました。',
      originalText: 'むかし むかし、ある ところに おじいさんと おばあさんが すんでいました。\n\nおじいさんは やまへ しばかりに、おばあさんは かわへ せんたくに いきました。',
      currentText: 'むかし むかし、ある ところに おじいさんと おばあさんが すんでいました。\n\nおじいさんは やまへ しばかりに、おばあさんは かわへ せんたくに いきました。',
      alt: 'おじいさんが山へしばかりに行き、おばあさんが川で洗濯をしている穏やかな田舎の風景',
      isModified: false,
    },
    {
      id: 3,
      pageNumber: 3,
      pageRole: '不思議なものが届く',
      fixedElements: ['大きな桃が川を流れてくること'],
      freeElements: ['桃の大きさ', '川の様子', '周囲の風景'],
      illustration: '/images/momotaro/page-03.jpg',
      text: 'おばあさんが せんたくを していると、かわかみから おおきな ももが どんぶらこ どんぶらこと ながれてきました。\n\n「まあ、なんて おおきな ももでしょう！」',
      originalText: 'おばあさんが せんたくを していると、かわかみから おおきな ももが どんぶらこ どんぶらこと ながれてきました。\n\n「まあ、なんて おおきな ももでしょう！」',
      currentText: 'おばあさんが せんたくを していると、かわかみから おおきな ももが どんぶらこ どんぶらこと ながれてきました。\n\n「まあ、なんて おおきな ももでしょう！」',
      alt: 'おばあさんが川で大きな桃が流れてくるのを驚いて見つける',
      isModified: false,
    },
    {
      id: 4,
      pageNumber: 4,
      pageRole: '主人公誕生',
      fixedElements: ['桃から男の子が生まれること'],
      freeElements: ['赤ちゃんの様子', '驚き方', '名前の由来'],
      illustration: '/images/momotaro/page-04.jpg',
      text: 'おうちで ももを きってみると、なんと なかから げんきな おとこのこが うまれました。\n\n「ももから うまれたから、ももたろうと なまえを つけましょう」',
      originalText: 'おうちで ももを きってみると、なんと なかから げんきな おとこのこが うまれました。\n\n「ももから うまれたから、ももたろうと なまえを つけましょう」',
      currentText: 'おうちで ももを きってみると、なんと なかから げんきな おとこのこが うまれました。\n\n「ももから うまれたから、ももたろうと なまえを つけましょう」',
      alt: 'おじいさんとおばあさんが桃から生まれた元気な赤ちゃんを見て驚き喜んでいる',
      isModified: false,
    },
    {
      id: 5,
      pageNumber: 5,
      pageRole: '成長と決意',
      fixedElements: ['ももたろうが成長し鬼退治を決意すること'],
      freeElements: ['成長の様子', '決意の表現', '性格描写'],
      illustration: '/images/momotaro/page-05.jpg',
      text: 'ももたろうは ぐんぐん おおきく つよく そだちました。\n\nある ひ、「おにが しまへ おにたいじに いってきます！」と いいました。',
      originalText: 'ももたろうは ぐんぐん おおきく つよく そだちました。\n\nある ひ、「おにが しまへ おにたいじに いってきます！」と いいました。',
      currentText: 'ももたろうは ぐんぐん おおきく つよく そだちました。\n\nある ひ、「おにが しまへ おにたいじに いってきます！」と いいました。',
      alt: 'たくましく成長したももたろうが力強いポーズを取っている',
      isModified: false,
    },
    {
      id: 6,
      pageNumber: 6,
      pageRole: '旅立ち',
      fixedElements: ['きびだんごを持って旅立つこと'],
      freeElements: ['持ち物', '見送りの様子', '旅立ちの表情'],
      illustration: '/images/momotaro/page-06.jpg',
      text: 'おばあさんは にほんいちの きびだんごを つくって もたせました。\n\n「いってらっしゃい、きを つけてね」\n\nおじいさんと おばあさんが みおくりました。',
      originalText: 'おばあさんは にほんいちの きびだんごを つくって もたせました。\n\n「いってらっしゃい、きを つけてね」\n\nおじいさんと おばあさんが みおくりました。',
      currentText: 'おばあさんは にほんいちの きびだんごを つくって もたせました。\n\n「いってらっしゃい、きを つけてね」\n\nおじいさんと おばあさんが みおくりました。',
      alt: 'ももたろうがきびだんごの包みを腰につけ、手を振って出発する。おじいさんとおばあさんが門で見送っている',
      isModified: false,
    },
    {
      id: 7,
      pageNumber: 7,
      pageRole: 'いぬと出会う',
      fixedElements: ['いぬが仲間になること'],
      freeElements: ['出会いの場所', '状況', 'いぬの性格'],
      illustration: '/images/momotaro/page-07.jpg',
      text: 'みちの とちゅうで、いぬに であいました。\n\n「ももたろうさん、きびだんごを ひとつ くださいな。おともします！」\n\nいぬは なかまに なりました。',
      originalText: 'みちの とちゅうで、いぬに であいました。\n\n「ももたろうさん、きびだんごを ひとつ くださいな。おともします！」\n\nいぬは なかまに なりました。',
      currentText: 'みちの とちゅうで、いぬに であいました。\n\n「ももたろうさん、きびだんごを ひとつ くださいな。おともします！」\n\nいぬは なかまに なりました。',
      alt: '道の途中でももたろうがいぬにきびだんごをあげている',
      isModified: false,
    },
    {
      id: 8,
      pageNumber: 8,
      pageRole: 'さる・きじと出会う',
      fixedElements: ['さるときじが仲間になること'],
      freeElements: ['出会いの場所', '状況', 'さるときじの性格'],
      illustration: '/images/momotaro/page-08.jpg',
      text: 'つぎに さると きじにも であいました。\n\n「きびだんごを ひとつ くださいな。おともします！」\n\nみんな なかまに なって、よにんで すすみました。',
      originalText: 'つぎに さると きじにも であいました。\n\n「きびだんごを ひとつ くださいな。おともします！」\n\nみんな なかまに なって、よにんで すすみました。',
      currentText: 'つぎに さると きじにも であいました。\n\n「きびだんごを ひとつ くださいな。おともします！」\n\nみんな なかまに なって、よにんで すすみました。',
      alt: 'ももたろう、いぬ、さる、きじの4人が楽しそうに道を歩いている',
      isModified: false,
    },
    {
      id: 9,
      pageNumber: 9,
      pageRole: '海を渡る',
      fixedElements: ['船で鬼ヶ島へ向かうこと'],
      freeElements: ['海の様子', '船の描写', '鬼ヶ島の見え方'],
      illustration: '/images/momotaro/page-09.jpg',
      text: 'ももたろうたちは ふねに のって、うみを わたりました。\n\nとおくに おにが しまが みえてきました。\n\n「あれが おにが しまだ！」',
      originalText: 'ももたろうたちは ふねに のって、うみを わたりました。\n\nとおくに おにが しまが みえてきました。\n\n「あれが おにが しまだ！」',
      currentText: 'ももたろうたちは ふねに のって、うみを わたりました。\n\nとおくに おにが しまが みえてきました。\n\n「あれが おにが しまだ！」',
      alt: 'ももたろうと動物の仲間たちが船に乗って海を渡り、遠くに鬼ヶ島が見える',
      isModified: false,
    },
    {
      id: 10,
      pageNumber: 10,
      pageRole: '鬼ヶ島上陸',
      fixedElements: ['鬼ヶ島に到着すること'],
      freeElements: ['門の描写', '鬼たちの様子', '雰囲気'],
      illustration: '/images/momotaro/page-10.jpg',
      text: 'おにが しまに つきました。おおきな もんを くぐると、おにたちが まっていました。\n\n「なにものだ！」おにたちが おおごえを だしました。',
      originalText: 'おにが しまに つきました。おおきな もんを くぐると、おにたちが まっていました。\n\n「なにものだ！」おにたちが おおごえを だしました。',
      currentText: 'おにが しまに つきました。おおきな もんを くぐると、おにたちが まっていました。\n\n「なにものだ！」おにたちが おおごえを だしました。',
      alt: 'ももたろうたちが鬼ヶ島の大きな門の前に立ち、中から鬼たちがこちらを見ている',
      isModified: false,
    },
    {
      id: 11,
      pageNumber: 11,
      pageRole: '戦いと勝利',
      fixedElements: ['仲間と力を合わせて鬼に勝つこと'],
      freeElements: ['戦い方', '敵の特徴', '展開'],
      illustration: '/images/momotaro/page-11.jpg',
      text: 'ももたろうと なかまたちは ちからを あわせて たたかいました。\n\nいぬは かみつき、さるは ひっかき、きじは つつきました。\n\n「まいった！ まいった！」おにたちは こうさんしました。',
      originalText: 'ももたろうと なかまたちは ちからを あわせて たたかいました。\n\nいぬは かみつき、さるは ひっかき、きじは つつきました。\n\n「まいった！ まいった！」おにたちは こうさんしました。',
      currentText: 'ももたろうと なかまたちは ちからを あわせて たたかいました。\n\nいぬは かみつき、さるは ひっかき、きじは つつきました。\n\n「まいった！ まいった！」おにたちは こうさんしました。',
      alt: 'ももたろうと仲間たちが鬼たちと勇敢に戦い、鬼たちが降参している',
      isModified: false,
    },
    {
      id: 12,
      pageNumber: 12,
      pageRole: 'ハッピーエンド',
      fixedElements: ['ハッピーエンドで終わること'],
      freeElements: ['結末の詳細', '宝物', '帰り道'],
      illustration: '/images/momotaro/page-12.jpg',
      text: 'ももたろうたちは たからものを もって おうちに かえりました。\n\nおじいさんと おばあさんは おおよろこび。\n\nみんなで なかよく しあわせに くらしました。\n\nめでたし めでたし。',
      originalText: 'ももたろうたちは たからものを もって おうちに かえりました。\n\nおじいさんと おばあさんは おおよろこび。\n\nみんなで なかよく しあわせに くらしました。\n\nめでたし めでたし。',
      currentText: 'ももたろうたちは たからものを もって おうちに かえりました。\n\nおじいさんと おばあさんは おおよろこび。\n\nみんなで なかよく しあわせに くらしました。\n\nめでたし めでたし。',
      alt: 'ももたろうが宝物を持って帰り、おじいさんとおばあさんと動物の仲間たちがみんなで喜んでいる',
      isModified: false,
    },
  ],
}
